### ISSUE TITLE
Failed to add members to channel

### ISSUE THREAD

**Issue by AndyGreenwell94** [GetStream/stream-chat-python#36]
Recently we found that we cannot add more than 100 users to the channel. No exceptions has been raised. We tried adding them one by one instead of batching by 99 users, but still they are not added to that channel. Any suggestions?

gz#5696

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5696'>Zendesk ticket #5696</a>:<br><br>Hi Andy

Thanks for reaching out to us.
Can you please share the AppID and UserID where you are experiencing issues with.

Cheers
Seetha

**Comment by AndyGreenwell94** [comment]
> Can you please share the AppID and UserID where you are experiencing issues with

AppID is 85053
I'm not sure about UserID, but probably it's 40230

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5696'>Zendesk ticket #5696</a>:<br><br>Hello, the maximum users you can add to a channel in a single API call is 100. You can add more with subsequent API calls.

**Comment by AndyGreenwell94** [comment]
> Hello, the maximum users you can add to a channel in a single API call is 100. You can add more with subsequent API calls.

We batch users to add. But we cannot add even 1 user when 100 was already added.

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5696'>Zendesk ticket #5696</a>:<br><br>Hi Andy

I am trying to understand a few things since there are no exceptions raised.

Are you using queryMembers endpoint to fetch all your users?
If yes, queryMembers by default returns 100 users. You might want to paginate in here.

You might want to try setting the offset parameter. By default, the offset parameter is 0 and the default limit is 100. Try changing these values and am sure you would be able to figure out you can add more and retrieve all the users.

Here are some places to look for -
https://getstream.io/chat/docs/query_members/?language=js#response
https://getstream.io/chat/docs/query_members/?language=js#query-options
https://getstream.io/chat/docs/query_members/?language=js

Please let us know how you go.

Cheers
Seetha

**Comment by AndyGreenwell94** [comment]
> If yes, queryMembers by default returns 100 users. You might want to paginate in here.

As we are using python sdk, the only possibility to fetch channel members is to query channel itself. We don't see users being added after 100 first users.

**Comment by AndyGreenwell94** [comment]
So just to confirm we are talking about the same issue here are steps.

- Create Channel
- Add Certain amount of users to it. It could be any number of users but in case it's more then 99 users to add, we do it in batches by maximum of 99 users per request. For this we use [this method](https://getstream.io/chat/docs_rest/#update-channel) which is `Channel.add_members([user_ids])` method in python SDK.
- If we have ~100 users in channel, we cannot add any more using this method. I've tried adding them one by one and in smaller batches for 30 users per request, but looks like no more users were added to channel. 
- In order to check, if users were added, we call [this method](https://getstream.io/chat/docs_rest/#query-channels), which is `Channel.query()` in python SDK. It returns only ~100 of added members.

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5696'>Zendesk ticket #5696</a>:<br><br>Hi Andy

Thanks for your patience.
Can you please let us know your App ID and the Channel Id where you are trying to add more than 100 users? Thanks.

cheers
Seetha

**Comment by BorisBidus** [comment]
Hi Stephen
App ID: 85053
Channel ID: 391

**Comment by ferhatelmas** [comment]
@BorisBidus default member limit is 100 without pagination, that's why you see up to 100.
You can find how to paginate here: https://getstream.io/chat/docs/channel_pagination/?language=python

That's being said, we will push query members feature to SDK too.
